server:
  port: 8080
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
          - id: players
            uri: ${PLAYERS_URI:lb://football}
            predicates:
              - Path=/api/players/**
            filters:
              - StripPrefix=1
          - id: albums
            uri: ${ALBUMS_URI:lb://albums}
            predicates:
              - Path=/api/albums/**
            filters:
              - StripPrefix=1
          - id: admin
            uri: lb://admin-server
            predicates:
              - Path=/admin/**
            filters:
              - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/